export const Data = [
  {
    sha: "c50531bbbc6e902949778787d0935d9becba0ce0",
    node_id: "C_kwDOKYhJz9oAKGM1MDUzMWJiYmM2ZTkwMjk0OTc3ODc4N2QwOTM1ZDliZWNiYTBjZTA",
    commit: {
      author: {
        name: "Gustavo Morillo",
        email: "gustavomorillo@gmail.com",
        date: "2023-09-26T20:09:11Z",
      },
      committer: {
        name: "Gustavo Morillo",
        email: "gustavomorillo@gmail.com",
        date: "2023-09-26T20:09:11Z",
      },
      message: "style: :lipstick: Add skeleton css to better UI and Loading spinner",
      tree: {
        sha: "0a475ce709f95f681b11ce58b74eb47b964a99da",
        url: "https://api.github.com/repos/gustavomorillo/full-time-force-test/git/trees/0a475ce709f95f681b11ce58b74eb47b964a99da",
      },
      url: "https://api.github.com/repos/gustavomorillo/full-time-force-test/git/commits/c50531bbbc6e902949778787d0935d9becba0ce0",
      comment_count: 0,
      verification: {
        verified: false,
        reason: "unsigned",
        signature: null,
        payload: null,
      },
    },
    url: "https://api.github.com/repos/gustavomorillo/full-time-force-test/commits/c50531bbbc6e902949778787d0935d9becba0ce0",
    html_url: "https://github.com/gustavomorillo/full-time-force-test/commit/c50531bbbc6e902949778787d0935d9becba0ce0",
    comments_url:
      "https://api.github.com/repos/gustavomorillo/full-time-force-test/commits/c50531bbbc6e902949778787d0935d9becba0ce0/comments",
    author: {
      login: "gustavomorillo",
      id: 47190430,
      node_id: "MDQ6VXNlcjQ3MTkwNDMw",
      avatar_url: "https://avatars.githubusercontent.com/u/47190430?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/gustavomorillo",
      html_url: "https://github.com/gustavomorillo",
      followers_url: "https://api.github.com/users/gustavomorillo/followers",
      following_url: "https://api.github.com/users/gustavomorillo/following{/other_user}",
      gists_url: "https://api.github.com/users/gustavomorillo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/gustavomorillo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/gustavomorillo/subscriptions",
      organizations_url: "https://api.github.com/users/gustavomorillo/orgs",
      repos_url: "https://api.github.com/users/gustavomorillo/repos",
      events_url: "https://api.github.com/users/gustavomorillo/events{/privacy}",
      received_events_url: "https://api.github.com/users/gustavomorillo/received_events",
      type: "User",
      site_admin: false,
    },
    committer: {
      login: "gustavomorillo",
      id: 47190430,
      node_id: "MDQ6VXNlcjQ3MTkwNDMw",
      avatar_url: "https://avatars.githubusercontent.com/u/47190430?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/gustavomorillo",
      html_url: "https://github.com/gustavomorillo",
      followers_url: "https://api.github.com/users/gustavomorillo/followers",
      following_url: "https://api.github.com/users/gustavomorillo/following{/other_user}",
      gists_url: "https://api.github.com/users/gustavomorillo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/gustavomorillo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/gustavomorillo/subscriptions",
      organizations_url: "https://api.github.com/users/gustavomorillo/orgs",
      repos_url: "https://api.github.com/users/gustavomorillo/repos",
      events_url: "https://api.github.com/users/gustavomorillo/events{/privacy}",
      received_events_url: "https://api.github.com/users/gustavomorillo/received_events",
      type: "User",
      site_admin: false,
    },
    parents: [
      {
        sha: "123ad3140760623d9810d4af227ff064923fb7b9",
        url: "https://api.github.com/repos/gustavomorillo/full-time-force-test/commits/123ad3140760623d9810d4af227ff064923fb7b9",
        html_url:
          "https://github.com/gustavomorillo/full-time-force-test/commit/123ad3140760623d9810d4af227ff064923fb7b9",
      },
    ],
  },
];
